spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
logging:
  level:
    root: INFO
    com.bruce.services.user_service.UserServiceApplication: TRACE


